jahorwitz/slopopedia

backend/.keystone/config.js
backend/keystone.ts
backend/migrations/20230818125335_init_post/migration.sql
backend/migrations/20230820124955_init_post_schema/migration.sql
backend/schema.graphql
backend/schema.prisma
backend/schema.ts

defined post schema object
[Jira Ticket - Slop-30](https://apiary-edtonomy.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-30)

feat: post schema definition

---

.github/workflows/deploy-prod copy.yml
.github/workflows/deploy-storybook copy.yml
src/components/Button/Button.jsx
src/components/Header.jsx
src/components/Keyword.jsx
src/components/Modal.jsx
src/components/MovieCard.jsx
src/components/MovieCardList.jsx
src/components/protected-route.jsx
src/components/tab-list.jsx
src/components/tab-panels.jsx
src/components/tabber.jsx

fix: fixing failed deployment script

---

src/components/Footer.jsx
src/components/Footer.stories.jsx
src/components/form.jsx
src/components/form.stories.jsx

Started creating reusable form component. I have ran in to a roadblock with styling the component in Storybook.
[](https://apiary-edtonomy.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-4)

feat: reusable-form-component

---

src/components/header/header.jsx

- change `isLoggedIn` in `header.jsx` to local state variable, default value `false`
- set `isLoggedIn` to `true` only if a `currentUser` object exists or proper data is returned from `GET_USER_AUTHENTICATION` query
[SLOP-52](https://apiary-edtonomy.atlassian.net/browse/SLOP-52)

Fix/slop 52/clear invalid jwt

---

package-lock.json
src/components/header/header.jsx
src/routes/main-route.jsx

Changing the login and signup buttons to the user's username when scrolling down to the Mobile menu size, 1024px and below.
SLOP-23
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-23
- [x ] I have performed a self-review of my code
- [x ] If there are changes to components, I have added / updated automated tests

Fix/slop 23/improve mobile login

---

package-lock.json
src/components/header/header.jsx
src/routes/main-route.jsx

Improving the main page header.
- Changing the width of the main page header to the full width of the page.
- Fixing the login/signin underline not to be overlapping by changing the text size.
- Fixing the header image to span the full width of the page.
SLOP-22
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-22
- [x ] If there are changes to components, I have added / updated automated tests

fix: improving main page header

---

src/components/SubmitList.jsx

- update import statement to prevent build errors

refactor: update import statement

---

src/App.jsx
src/components/MoviePreviewModal.jsx
src/components/SubmitList.jsx
src/components/badge/badge.jsx
src/components/login-modal.jsx
src/components/modal/modal.jsx
src/components/signup-modal.jsx
src/graphql/index.js
src/routes/profile-route/watchlist-tabber.jsx

**Due to the absence of a Figma template tailored for mobile design, I had to rely on my own judgment to make adjustments. In the second screenshot (after the changes), the elements may appear larger than in the original. This difference is due to the varying screen sizes of the devices used to capture the screenshots; the actual size of the elements remains unchanged.**
- Incorporating Slop-19 Client Context into the main branch resulted in two errors. Firstly, the SubmitList.jsx file was still utilizing the outdated CurrentUserContext. Secondly, the line "export * from "./hook/useCurrentUser"" in the index.js file within the graphQL folder needed to be removed for the webpage to load properly.
- Signup Modal: Although the signup modal didn't encounter responsiveness issues, I observed a …

Fix/slop 27/improvement modal responsiveness

---

src/components/MovieCard.jsx
src/components/MovieCardList.jsx
src/components/keyword.jsx
src/routes/main-route.jsx
src/utils/constants.js

- Previously the size of movies was being passed as an object to the MovieCard. I adjusted the colSizes constant to have a size value associated with them, then carried that over to the parent div in MovieCard.
- Adjusted the max height of images to be 80vh.
[Slop-24/Improvement: Main Page Movie List](https://tripleten-apiary.atlassian.net/browse/SLOP-24?atlOrigin=eyJpIjoiMmY2MGM5NTU2NWI4NDYxZGFiYzBlOGZjNzg2YWVmNmEiLCJwIjoiaiJ9)

Feature/slop 24/main page movie list

---

src/page/blog/article-page.jsx

I fixed the typo in the success message that appears after creating a blog post.
slop-34

fix: blog post success message

---

src/components/movie-card/movie-card.stories.jsx
src/utils/constants.js

fix: fix storybook by bringing back in util constants

---

src/components/slop-fest-modal.jsx
src/routes/profile-route/profile-fests-route.jsx
src/store/client-context-provider.jsx

Checked for existence of location data (which is only available editing an existing slop fest) before trying to access location.pathname
[Ticket number 55](https://tripleten-apiary.atlassian.net/browse/SLOP-55)

Fix/slop 55/create new slop fest modal

---

src/store/client-context-provider.jsx

**Bug:** When 1st logging in, don't refresh the page. Try clicking a link in the header. You are automatically logged out. 
A simple change seems to have done the trick. I added **token** as a dependency to the useEffect that sets up authorization. That way when **token** changes, the useEffect will run again.
https://www.loom.com/share/252634dcdd4147ab98bdd95b9463c7d3
slop-41
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-41

fix slop-41: user logged out when clicking a link, after initial login

---

src/page/blog/articles-page.jsx
src/routes/blog-route/draft-route.jsx
src/routes/profile-route/profile-sidebar.jsx

Added conditional logic to only render blog writer links if logged in.

Fix / Slop 73 / Dont render blog writer links if guest

---

src/page/blog/articles-page.jsx
src/routes/blog-route/draft-route.jsx
src/routes/profile-route/profile-sidebar.jsx

Added conditional logic to only render blog writer links if logged in.

Ignore this PR

---

src/components/form/form.jsx
src/components/slop-fest-modal.jsx
src/page/blog/article-page.jsx
src/routes/submit-route/submit-slop-form.jsx

Before this change, on any given Combobox throughout the application, the user would be able to select the same choice from the dropdown more than once. I updated the way Form.Combobox behaves with the "list" prop it's provided. I also removed some unneeded code that was also partially causing this issue. 
**IMPORTANT NOTE**: I was ONLY able to test this setup on the submit-slop-form. I could not test it on the forms for creating a new fest or the form for a new Blog Post because all of those are currently broken and waiting for approval in other PRs. 
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-31

Fix/Slop-31/Combobox Allows For Doubles

---

src/page/blog/article-page.jsx

Update some instances of the variable name **data** to the correct **postData** name.
slop-85
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-85

Fix/Slop-85/Publishing Blog Posts

---

src/components/movie-preview-modal.jsx

Only render the publish button on slop drafts if the isAdmin property of a user is true.
https://tripleten-apiary.atlassian.net/browse/SLOP-86?atlOrigin=eyJpIjoiNTk0NjhlNWU3Mjc3NDdiYThkZjJhN2E5YWI4NzM0ZjEiLCJwIjoiaiJ9

Feature / Slop-86 / Prevent user from approving submitted slops

---

src/App.jsx
src/components/header/header.jsx
src/components/movie-preview-modal.jsx
src/hooks/use-movies.js
src/hooks/use-sounds.js
src/routes/main-route.jsx
src/store/movie-context-provider.jsx
src/store/movie-context.js
src/store/sound-context-provider.jsx
src/store/sound-context.js

Add a MovieContextProvider and a SoundContextProvider component. Add a click handler to the **I'm feeling sloppy** button, which routes the user to the homepage opens up a random movie's modal, and plays a hardcoded sound. 
slop-75
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-75

Feature/slop 75/I'm feeling sloppy functionality

---

package-lock.json
package.json
src/components/form/advanced-form-inputs/checkbox.jsx
src/components/form/advanced-form-inputs/controlledCheckbox.jsx
src/components/form/advanced-form-inputs/radio.jsx
src/hooks/index.js
src/hooks/use-debounce.js
src/routes/search-route.jsx

Added search page with full functionality for all filters described in the Figma design.
**NOTE:** There are issues with the `<MovieCard/>` and `<MovieCardList/>` components that are outside of the scope of this ticket. These include issues with the styling of the movie cards and an issue with the keys on movie cards potentially being duplicates. The issue with the movie cards could also have something to do with the create-movies script.
1. From the frontend directory, switch to the search filters branch (`git switch feature/slop-5/search-filters`)
2. `git pull`
3.  Seed local DB with movies and keywords using `BACKEND/scripts/create-movies.js` (see below section if you need help with that)
4. Navigate to search page and see if stuff breaks.
1. Open `BACKEND/Scripts/create-movies.js` and …

Feature/slop 5/search filters

---

src/routes/profile-route/profile-fests-route.jsx

Fixed CSS for the 'Fests' button and adjusted the page layout for medium and small screens.
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-81

Fix/slop 81/rsvp button on fest page

---

src/page/blog/article-page.jsx
src/page/blog/review-page.jsx

Protected draft deletion with the pre-existing delete confirmation modal.
https://tripleten-apiary.atlassian.net/browse/SLOP-80?atlOrigin=eyJpIjoiNmY1MDYzNWZkZjM1NDliZTkyZjI0ZWNiMjE4MDY5YjgiLCJwIjoiaiJ9

Feature / Slop 80 / Protect delete draft blog with modal

---

src/components/sidebar/sidebar-item.jsx
src/routes/fest-route/fest-sidebar.jsx

fixed the bug where you can't open the fest page 
slop-92

fix / slop-92/ create new slop and open it 

---

src/components/header/header.jsx

added data-test-id to header component
slop-104
link: https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-104

feat: add test ids to html components

---

src/components/movie-preview-modal.jsx

added data-test-ids for testing to movie-preview-modal.jsx
ticket: slop-213
link: https://tripleten-apiary.atlassian.net/browse/SLOP-213

test: add data-test-ids to movie-preview-modal.jsx for testing purposes

---

src/components/delete-movie-modal.jsx

- addition of data test ids
slop ticket: slop-104
link: https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-217

feat: add data-test-id to html elements in delete confirmation modal

---

src/components/movie-card/movie-card.jsx

added data-test-ids to move-card.jsx for testing
ticket: slop-214
link: https://tripleten-apiary.atlassian.net/browse/SLOP-214

test: add data-test-ids to movie-card.jsx for testing purposes

---

src/components/sound-card/sound-card.jsx

added data-test-id to sound-card.jsx for testing
ticket: slop-215
link: https://tripleten-apiary.atlassian.net/browse/SLOP-215

test: add data-test-ids to sound-card.jsx for testing purposes

---

src/components/delete-movie-modal.jsx
src/components/keyword.jsx

- add data test id to keywords 
slop ticket: slop-104
link: https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-219

Feature/slop 104/data test id keywords

---

src/components/delete-movie-modal.jsx
src/components/discussion-card.jsx
src/components/keyword.jsx

add data test id to discussion card
slop ticket: slop-104
link: https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-220

Feature/slop 104/data test id discussion card

---

src/routes/blog-route/article-route.jsx
src/routes/blog-route/articles-route.jsx
src/routes/blog-route/draft-route.jsx
src/routes/blog-route/review-route.jsx

Added the datta-test-id to the blog route
- [v ] I have performed a self-review of my code
- [ v] If there are changes to components, I have added / updated automated tests
- [ v] I have made any necessary updates to Storybook to accompany these changes
- [ v] I have commented my code, particularly in hard-to-understand areas
- [ v] I have made corresponding changes to the documentation
- [ v] My changes generate no new warnings

feat: add-datta-test-id-sub-blog-route

---

src/page/blog/article-page.jsx
src/page/blog/articles-page.jsx
src/page/blog/draft-page.jsx
src/page/blog/review-page.jsx

- [ v] I have performed a self-review of my code
- [ v] If there are changes to components, I have added / updated automated tests
- [ v] I have made any necessary updates to Storybook to accompany these changes
- [ v] I have commented my code, particularly in hard-to-understand areas
- [ v] I have made corresponding changes to the documentation
- [ v] My changes generate no new warnings

feat: slop 104 data test id sub page blog

---

src/routes/profile-route/profile-fests-route.jsx
src/routes/profile-route/profile-horizontal-menu.jsx
src/routes/profile-route/profile-route.jsx
src/routes/profile-route/profile-settings-route.jsx
src/routes/profile-route/profile-sidebar.jsx
src/routes/profile-route/watchlist-tab-list.jsx
src/routes/profile-route/watchlist-tabber.jsx

- [ v] I have performed a self-review of my code
- [ v] If there are changes to components, I have added / updated automated tests
- [ v] I have made any necessary updates to Storybook to accompany these changes
- [ v] I have commented my code, particularly in hard-to-understand areas
- [ v] I have made corresponding changes to the documentation
- [ v] My changes generate no new warnings

feat: data-test-id-sub-profile-route

---

src/components/movie-card-list.jsx
src/graphql/get-movies.js
src/routes/search-route.jsx

- Used keystone functionality with GraphQL API to implement pagination to the movies list
- Added new query in frontend to handle the pagination mechanism
issue number: Slop-108
Jira link: https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-108

feat: add pagination mechanism to movies list

---

src/routes/fest-route/fest-discussion.jsx

- [ v] I have performed a self-review of my code
- [ v] If there are changes to components, I have added / updated automated tests
- [ v] I have made any necessary updates to Storybook to accompany these changes
- [v ] I have commented my code, particularly in hard-to-understand areas
- [ v] I have made corresponding changes to the documentation
- [ v] My changes generate no new warnings

feat: add test id tags to fest discussion route

---

src/page/blog/article-page.jsx

made publish button on route /articles/create borderless
slop-125
link - https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-125

feat: took away the border for the publish button on /articles/create

---

src/components/button/button.jsx
src/page/blog/article-page.jsx

made save drafts button at route /articles/create have a transparent background
PS i also made the gap between the two buttons match figma of 20px
slop-123
link - https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-123

feat: made save drafts button at route /articles/create transparent background

---

src/page/blog/article-page.jsx

just changed the order of slops and keywords form inputs on route articles/create
slop - 127
link -  https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?cloudId=7e21ac7a-fb65-47c8-a8d4-37c6004ad012&selectedIssue=SLOP-127

feat: changed the order of slops and keywords

---

src/components/header/header.jsx

submit slop nav link will now only show in header if you are logged in if not logged in it will be hidden
ticket = slop-120
link = https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?cloudId=7e21ac7a-fb65-47c8-a8d4-37c6004ad012&selectedIssue=SLOP-120

feat: submit slop in nav links will only show if logged in

---

src/components/login-modal.jsx

error messages from an incorrect username or password now fully display
email username displays the error message as well
empty username or password will display the specific error message
https://github.com/jahorwitz/slopopedia/compare/main...feature/slop-112/no-login-error-message
slop 112
- [ X] I have performed a self-review of my code
- [ x] If there are changes to components, I have added / updated automated tests
- [ x] I have made any necessary updates to Storybook to accompany these changes
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings

feat: login error message display

---

src/components/form/advanced-form-inputs/dropdown.jsx
src/components/form/advanced-form-inputs/textArea.jsx
src/components/movie-card/movie-card.jsx
src/components/movie-preview-modal.jsx
src/graphql/create-movie.js
src/graphql/get-fest.js
src/graphql/get-movies.js
src/graphql/get-user-authentication.js
src/graphql/get-users.js
src/graphql/mutations/edit-slop-submission.js
src/graphql/mutations/fest/update-fest.js
src/graphql/queries/get-movie-by-id.js
src/graphql/update-user.js
src/routes/browse-route.jsx
src/routes/submit-route/submit-route.jsx
src/routes/submit-route/submit-slop-form.jsx

**RELATED BACK END PR:** [HERE](https://github.com/jahorwitz/slopopedia-api/pull/20)
Refactored numerous components to reflect changes outlined in the corresponding backend pr.
1. Run backend branch mentioned above.
2. `git switch feature/slop-42/image-uploads-for-slop-submissions` 
3. test submit slop page.
4. view home page to confirm submission.
**SCREENSHOT:** 
https://tripleten-apiary.atlassian.net/browse/SLOP-42?atlOrigin=eyJpIjoiMjJjYjdlNTU1MTljNGIxMDgxMjkzNzQ5MjM3YTljYzIiLCJwIjoiaiJ9

Feature/slop 42/image uploads for slop submissions

---

src/components/movie-card/movie-card.jsx
src/routes/submit-route/submitted-slops/submitted-list.jsx

I added a check to the MovieCard component that checks if it is being rendered in the submit-a-slop-list component, if it is, it will render the movie card at a specific size based on the figma design.
Slop-39
[slop-39 ticket link](https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?atlOrigin=eyJwIjoiaiIsImkiOiJiMTE1YWM3NWEwMmU0MTE4OTRlN2U1MmY5NzFlZmZjZiJ9&cloudId=7e21ac7a-fb65-47c8-a8d4-37c6004ad012&selectedIssue=SLOP-39)

refactor: fix linting errors

---

package-lock.json
src/components/footer/footer.jsx

Login to the application
Navigate to the Profile page.
Click on the “Cookies” link on the footer of the page.
**The link is not clickable. The user stays on the same page. I removed the cookies link**
Profile Footer: The "Cookies" link does not work.[SLOP-240](https://tripleten-apiary.atlassian.net/browse/SLOP-240)

fix- removed cookies link slop-240
