src/graphql/index.js
Removed an unnecessary export line from `/src/graphql/index.js` that was causing the build to fail
=> refactor: remove export from graphql index.js

src/components/login-modal.jsx, src/components/signup-modal.jsx
Description:
Added the type='password' attribute to the login and signup modals to prevent other's from seeing it. Also fixed popover responsiveness to ensure it can undergo screen responsiveness and keep a clean design. The rest of the items on this ticket were covered in the 'fix/slop-27/improvement-modal-responsiveness' ticket. 
- Added the type="password' attribute to the password input on the Login and Signup Modals to prevent passwords from showing up when user types it in (as per Figma)
- Changed the popover text size so that it is a bit more responsive as the modal undergoes screen changes. 
[Slop 26: Improvement: Popover styling on Login Modal](https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-26)
=> Slop 26: Improvement: Popover styling on Login Modal

src/page/blog/article-page.jsx
The "keywords" dropdown on the New Blog form was displaying in an unappealing way. By updated the z-index on the input the display is not more user friendly. 
Fix Keywords z-index on Write a blog post page
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-46
=> fix/slop-46/adjust z-index on keyword dropdown

src/page/blog/article-page.jsx, src/page/blog/articles-page.jsx
When the user would attempt to create a new blog post, the "Slops" dropdown was not functional. I updated the way movies/slops were being queried and fixed the issue. Now a list of movies/slops will populate when the user clicks on the dropdown arrow like expected. 
Slop-47-Fix Slop Dropdown When Writing a blog post
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-47
=> Fix/slop 47/slop dropdown on blog post

src/components/movie-card/movie-card.jsx
I updated the style of the div responsible for setting the relative position necessary for the absolutely positioned keywords to use for correct placement. Screenshot attached to show what my local homepage looks like after this change. 
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-58
=> fix/slop-58/positioning of movie tags/keywords

src/routes/submit-route/submit-slop-form.jsx
All keywords were being mapped to the form submission rather than only the keywords selected in the combo box. Also changed some minor capitalization to match form input naming convention.
[SLOP-59](https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-59)
=> Fix/SLOP-59/Keyword Tagging when Submitting a Slop

src/routes/blog-route/draft-route.jsx
A very quick change to the z-index, so that the links shown in the image on jira, are now clickable.
slop-60
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-60
=> fix: slop-60 / Side bar links on Draft List Page are not Clickable

src/App.jsx, src/components/blog/draft.jsx, src/page/blog/article-page.jsx, src/page/blog/review-page.jsx, src/routes/blog-route/article-route.jsx, src/routes/blog-route/draft-route.jsx
Added a delete button to be able to delete Draft Blog Posts.
The delete button also currently shows up when editing a published blog post and is functional as well. But if we don't want a delete button there, I can easily remove that.
Update: I initially had 3 routes for the Article component: create, edit-published, and edit-draft. Upon request, I deleted a route and changed it back to the initial 2 routes.
Slop-35. Add a button to delete draft blog posts
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-35
=> Feature/slop 35/delete draft blog post

src/routes/submit-route/submit-slop-form.jsx
Edit both releaseYear and runtime slop submission inputs to only accept 4 and 3 digits respectively. 
In the case of making these required fields, as the story seems to suggest, when reviewing the design spec on figma, Release Year and Runtime do not seem to be required fields. For that reason I left them as not required, but I can easily change this if need be, just let me know one way or another. 
Slop-65
https://tripleten-apiary.atlassian.net/browse/SLOP-65?atlOrigin=eyJpIjoiNWJmNDYwZjRjZmEzNDUwMjhkZWIyNmI2ZjYyYTdiNGEiLCJwIjoiaiJ9
=> Fix / Slop-65 / Submit slop form validation

src/routes/fest-route/fest-sidebar.jsx
A quick fix so that invitees of a fest, can no longer see the button **Edit dates and guests**.
slop-77
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-77
=> Feat/Slop-77 Fest Invitee Should Not Be able to Edit Date or Guests

src/components/slop-fest-modal.jsx
The fest modal can not be submitted without first editing the title.
slop 76
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-76
=> Fix/slop-76 Can't edit fest without editing title

src/routes/blog-route/draft-route.jsx
Title is self-explanatory. Simple removal of the "drafts" link from the drafts page.
=> Fix / Slop-74 / Remove draft links from drafts page

src/page/blog/article-page.jsx
A quick fix, so that now when a user creates a new draft blog, instead of showing the success page, it now redirects the user to the drafts page.
slop-82
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-82
=> Fix/slop-82/Redirect User After Creating a Draft Blog Post

src/components/movie-preview-modal.jsx
Add conditional rendering to userButtons in movie-preview-modal based on slop status
https://tripleten-apiary.atlassian.net/browse/SLOP-87?atlOrigin=eyJpIjoiN2FjZjAzMjQwNmYxNDMyMGI1NjM5OWQ4MTEwMzAxNGEiLCJwIjoiaiJ9
=> Fix / Slop-87 / Preview Slop Modal Should not Allow Watched It/Want It Buttons

src/components/id-protected-route.jsx, src/page/blog/article-page.jsx, src/routes/fest-route/fest-discussion.jsx, src/routes/fest-route/fest-route.jsx
Protect 3 routes: "/articles/:id/edit" , "/fests/:festId" , "/fests/:festId/discussion". 
The route "/articles/:id/edit", should only be viewable by the article author.
The routes "/fests/:festId" and "/fests/:festId/discussion", should only be viewable by the fest creator (who is naturally an invitee to their own fest) and any other invitees/attendees. 
**Testing:**
In order to test this, I recommend copying the url on one of these routes, when logged in as an authorized user. And then logging in to a user that shouldn't have access, and pasting the url into the browser. If unauthorized, you should be redirected to the home page.
**Note** that if you create a fest in the Keystone UI, the user that you make the creator of the fest, is not automatically made an invitee or attendee. …
=> feature/slop-79/Protect routes that require a specific user(s)

src/components/header/header.jsx
Utilize react-router-dom "Link" component to avoid refreshing the page when the profile page is selected.
https://tripleten-apiary.atlassian.net/browse/SLOP-89?atlOrigin=eyJpIjoiNjcwZWM4NTNhODEzNDM4NGJlNWE5MWM3OGQ4MGE3MjEiLCJwIjoiaiJ9
=> Fix / Slop 89 / Don't reload whole page when viewing profile

src/components/movie-card-list.jsx, src/components/movie-card/movie-card.jsx
- Added styling to the movie cards to match the Figma design on the homepage. 
- Altered grid system to adjust for smaller screens - needs further work I believe perhaps in a future ticket.
Figma Design: https://www.figma.com/design/NDxE2DhULzua1KRFG6d4hA/Slopopedia?node-id=248-10750&t=HsHmTalBRM0JAnUx-0
Slop-106: https://tripleten-apiary.atlassian.net/browse/SLOP-106?atlOrigin=eyJpIjoiNDY1NTY0NjY3MTQ2NGJiOWJkNDU2ZGMxZDdhNGE4N2MiLCJwIjoiaiJ9
=> Fix/slop 106/image styling

src/components/blog/post.jsx, src/components/footer/footer.jsx, src/page/blog/review-page.jsx
Blog articles page text previews no longer overflow from the parent post container (see screenshots in slop board to compare)
Blog post review page no longer has clipping footer and sits under the pages content
https://tripleten-apiary.atlassian.net/browse/SLOP-122
=> Fix/slop 122 & slop 127/blog article short preview/intersecting footer fix

src/App.jsx, src/graphql/create-movie.js, src/routes/slop-route/edit-submitted-slop-route.jsx, src/routes/submit-route/submit-slop-form.jsx, src/routes/submit-route/submitted-slops/submitted-list.jsx
… having to refresh
*changed the submit-slop-form.jsx when initializing createMovie and using the mutation from query it adds the newly created movie to the cache allowing it to be on the edit page
*also had to switch up the CREATE_MOVIE 'gql' mutation to fix some of the errors 
slop-30
https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-30
=> fix: the edit modal when opened will have newly created movie without having to refresh page

src/components/form/form.jsx
Added a maximum character limit to the input fields of the Sign Up modal
Slop-111 [https://tripleten-apiary.atlassian.net/browse/SLOP-111]
=> fix: Sign Up input field with max character limit

src/routes/profile-route/profile-settings-route.jsx
When onSubmit fired, the returned data in res that was being used to setValue was empty, so when trying to save new user data again, it would say that the field was empty. The correct data is now being used to fill the fields.
[242](https://tripleten-apiary.atlassian.net/browse/SLOP-242)
=> fix: profile-settings-route.jsx correct data now used in setValue from res in onSubmit
